version: '3.6'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456aA@
      - POSTGRES_DB=faceid
    ports:
      - 5432:5432
    volumes:
      - ./database/postgres_init.sql:/docker-entrypoint-initdb.d/file.sql
      - ./data/postgresql-data:/var/lib/postgresql/data

  milvus:
    image: milvusdb/milvus:1.1.1-cpu-d061621-330cc6
    container_name: milvus
    network_mode: "host"
    restart: always
    ports:
      - 19530:19530
      - 19121:19121
    volumes:
      - ./server_config.yaml:/var/lib/milvus/conf/server_config.yaml
      - ./data/milvus/db:/var/lib/milvus/db
      - ./data/milvus/conf:/var/lib/milvus/conf
      - ./data/milvus/logs:/var/lib/milvus/logs
      - ./data/milvus/wal:/var/lib/milvus/wal
  # faceapi:
  #   image: face-api:v1.0
  #   container_name: face_api
  #   restart: always
  #   network_mode: "host"
  #   tty: true
  #   volumes:
  #    - /etc/hosts:/etc/hosts 
  #    - ./app:/opt/faceapi/service-api/
