# This file was generated by Nuitka and describes the types of the
# created shared library.

# At this time it lists only the imports made and can be used by the
# tools that bundle libraries, including Nuitka itself. For instance
# standalone mode usage of the created library will need it.

# In the future, this will also contain type information for values
# in the module, so IDEs will use this. Therefore please include it
# when you make software releases of the extension module that it
# describes.

import logging
import fastapi
import common.database
import common.database.database
import configs.configs
import dependencies
import utils.logging
import endpoint.enroll
import endpoint.enroll2
import endpoint.update_localUserId
import endpoint.update_userId
import endpoint.delete_localUserId
import endpoint.delete_userId
import endpoint.get_list_registers
import endpoint.get_localUserId
import endpoint.search_user_by_face
import endpoint.search_user_by_fhd_image
import endpoint.matching
import endpoint.milvus_endpoint
import endpoint.update_url

# This is not Python source even if it looks so. Make it clear for
# now. This was decided by PEP 484 designers.
__name__ = ...

